# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import match_pb2 as match__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in match_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatchServiceStub(object):
    """注:订阅档位不在本 proto 重复定义,GetQuotaResponse.tier 用 string 透传
    取值 "FREE" / "WEEKLY" / "MONTHLY" / "YEARLY",权威定义见 payment.proto SubscriptionTier
    (避免 enum 全局 namespace 冲突 ── proto3 enum 值是 C++ scoping siblings)

    =====================================================================
    2. MatchService
    =====================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTodayFeed = channel.unary_unary(
                '/MatchService/GetTodayFeed',
                request_serializer=match__pb2.GetTodayFeedRequest.SerializeToString,
                response_deserializer=match__pb2.GetTodayFeedResponse.FromString,
                _registered_method=True)
        self.Swipe = channel.unary_unary(
                '/MatchService/Swipe',
                request_serializer=match__pb2.SwipeRequest.SerializeToString,
                response_deserializer=match__pb2.SwipeResponse.FromString,
                _registered_method=True)
        self.SuperHi = channel.unary_unary(
                '/MatchService/SuperHi',
                request_serializer=match__pb2.SuperHiRequest.SerializeToString,
                response_deserializer=match__pb2.SuperHiResponse.FromString,
                _registered_method=True)
        self.ListMatches = channel.unary_unary(
                '/MatchService/ListMatches',
                request_serializer=match__pb2.ListMatchesRequest.SerializeToString,
                response_deserializer=match__pb2.ListMatchesResponse.FromString,
                _registered_method=True)
        self.GetQuota = channel.unary_unary(
                '/MatchService/GetQuota',
                request_serializer=match__pb2.GetQuotaRequest.SerializeToString,
                response_deserializer=match__pb2.GetQuotaResponse.FromString,
                _registered_method=True)
        self.ListFriendUserIds = channel.unary_unary(
                '/MatchService/ListFriendUserIds',
                request_serializer=match__pb2.ListFriendUserIdsRequest.SerializeToString,
                response_deserializer=match__pb2.ListFriendUserIdsResponse.FromString,
                _registered_method=True)
        self.ListLikesOfMe = channel.unary_unary(
                '/MatchService/ListLikesOfMe',
                request_serializer=match__pb2.ListLikesOfMeRequest.SerializeToString,
                response_deserializer=match__pb2.ListLikesOfMeResponse.FromString,
                _registered_method=True)
        self.RecordVisit = channel.unary_unary(
                '/MatchService/RecordVisit',
                request_serializer=match__pb2.RecordVisitRequest.SerializeToString,
                response_deserializer=match__pb2.RecordVisitResponse.FromString,
                _registered_method=True)
        self.ListVisitsOfMe = channel.unary_unary(
                '/MatchService/ListVisitsOfMe',
                request_serializer=match__pb2.ListVisitsOfMeRequest.SerializeToString,
                response_deserializer=match__pb2.ListVisitsOfMeResponse.FromString,
                _registered_method=True)


class MatchServiceServicer(object):
    """注:订阅档位不在本 proto 重复定义,GetQuotaResponse.tier 用 string 透传
    取值 "FREE" / "WEEKLY" / "MONTHLY" / "YEARLY",权威定义见 payment.proto SubscriptionTier
    (避免 enum 全局 namespace 冲突 ── proto3 enum 值是 C++ scoping siblings)

    =====================================================================
    2. MatchService
    =====================================================================
    """

    def GetTodayFeed(self, request, context):
        """拉当日 feed 下一批
        移动端固定每次 count=5;LPOP 即消费,二次过滤已 swipe 的 target;
        LIST 空时实时调 ColdStartService 重建 240 张
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Swipe(self, request, context):
        """提交一次 swipe(LEFT / RIGHT)
        RIGHT + 对方 BH 已右划过我 → 立即 match;RIGHT + 对方 DH → 进 15s-2min 延迟队列;
        幂等:同一(caller, target)重复 swipe 直接返回上次结果,不扣配额(防客户端 retry)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuperHi(self, request, context):
        """SuperHi(订阅赠送 1 次/天或扣 100 金币)
        BH/DH 均立即 match;扣金币时通过 client_request_id 防重发
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMatches(self, request, context):
        """我的匹配列表(分页)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuota(self, request, context):
        """配额查询(订阅档位 + 当日已用 / 剩余)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFriendUserIds(self, request, context):
        """post-service fanout 用:拉某 user 的所有匹配伙伴 user_id
        "匹配成功即好友";硬上限 1000(按 matched_at 倒序取最近的)
        caller 显式传 user_id,不走 metadata x-user-id ── 调用方是 system call
        (post-service async fanout 跨线程,无法继承 grpc metadata)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLikesOfMe(self, request, context):
        """"Likes of me" 列表:谁喜欢了我(真人 like 操作归档)
        数据源 like_record 表;RIGHT_SWIPE 和 SUPER_HI 都落,即时 match 也不删
        App 客户端拿到列表后自行去重或对已 match 的人打"已匹配" badge
        caller 走 metadata x-user-id(与 ListMatches 一致)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordVisit(self, request, context):
        """记录主页访问:App 端用户进入别人主页时调用,服务端 UPSERT visit_record
        自访问短路;失败 fail-open;同 (viewer,target) 重复调用累加 visit_count
        viewer_user_id 走 metadata x-user-id,target_user_id 显式传
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVisitsOfMe(self, request, context):
        """"Visits of me" 列表:谁访问过我的主页
        数据源 visit_record 表(UPSERT 累加,所以一人一行,visit_count 表示访问次数)
        按 last_visited_at 倒序;cursor = last_visited_at epoch ms
        caller 走 metadata x-user-id(与 ListMatches / ListLikesOfMe 一致)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTodayFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodayFeed,
                    request_deserializer=match__pb2.GetTodayFeedRequest.FromString,
                    response_serializer=match__pb2.GetTodayFeedResponse.SerializeToString,
            ),
            'Swipe': grpc.unary_unary_rpc_method_handler(
                    servicer.Swipe,
                    request_deserializer=match__pb2.SwipeRequest.FromString,
                    response_serializer=match__pb2.SwipeResponse.SerializeToString,
            ),
            'SuperHi': grpc.unary_unary_rpc_method_handler(
                    servicer.SuperHi,
                    request_deserializer=match__pb2.SuperHiRequest.FromString,
                    response_serializer=match__pb2.SuperHiResponse.SerializeToString,
            ),
            'ListMatches': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMatches,
                    request_deserializer=match__pb2.ListMatchesRequest.FromString,
                    response_serializer=match__pb2.ListMatchesResponse.SerializeToString,
            ),
            'GetQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuota,
                    request_deserializer=match__pb2.GetQuotaRequest.FromString,
                    response_serializer=match__pb2.GetQuotaResponse.SerializeToString,
            ),
            'ListFriendUserIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFriendUserIds,
                    request_deserializer=match__pb2.ListFriendUserIdsRequest.FromString,
                    response_serializer=match__pb2.ListFriendUserIdsResponse.SerializeToString,
            ),
            'ListLikesOfMe': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLikesOfMe,
                    request_deserializer=match__pb2.ListLikesOfMeRequest.FromString,
                    response_serializer=match__pb2.ListLikesOfMeResponse.SerializeToString,
            ),
            'RecordVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordVisit,
                    request_deserializer=match__pb2.RecordVisitRequest.FromString,
                    response_serializer=match__pb2.RecordVisitResponse.SerializeToString,
            ),
            'ListVisitsOfMe': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVisitsOfMe,
                    request_deserializer=match__pb2.ListVisitsOfMeRequest.FromString,
                    response_serializer=match__pb2.ListVisitsOfMeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatchService(object):
    """注:订阅档位不在本 proto 重复定义,GetQuotaResponse.tier 用 string 透传
    取值 "FREE" / "WEEKLY" / "MONTHLY" / "YEARLY",权威定义见 payment.proto SubscriptionTier
    (避免 enum 全局 namespace 冲突 ── proto3 enum 值是 C++ scoping siblings)

    =====================================================================
    2. MatchService
    =====================================================================
    """

    @staticmethod
    def GetTodayFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/GetTodayFeed',
            match__pb2.GetTodayFeedRequest.SerializeToString,
            match__pb2.GetTodayFeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Swipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/Swipe',
            match__pb2.SwipeRequest.SerializeToString,
            match__pb2.SwipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuperHi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/SuperHi',
            match__pb2.SuperHiRequest.SerializeToString,
            match__pb2.SuperHiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/ListMatches',
            match__pb2.ListMatchesRequest.SerializeToString,
            match__pb2.ListMatchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/GetQuota',
            match__pb2.GetQuotaRequest.SerializeToString,
            match__pb2.GetQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFriendUserIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/ListFriendUserIds',
            match__pb2.ListFriendUserIdsRequest.SerializeToString,
            match__pb2.ListFriendUserIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLikesOfMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/ListLikesOfMe',
            match__pb2.ListLikesOfMeRequest.SerializeToString,
            match__pb2.ListLikesOfMeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/RecordVisit',
            match__pb2.RecordVisitRequest.SerializeToString,
            match__pb2.RecordVisitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVisitsOfMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchService/ListVisitsOfMe',
            match__pb2.ListVisitsOfMeRequest.SerializeToString,
            match__pb2.ListVisitsOfMeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
