# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """==========================================
    4. gRPC Service 定义
    ==========================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProducts = channel.unary_unary(
                '/PaymentService/GetProducts',
                request_serializer=payment__pb2.GetProductsRequest.SerializeToString,
                response_deserializer=payment__pb2.GetProductsResponse.FromString,
                _registered_method=True)
        self.CreateOrder = channel.unary_unary(
                '/PaymentService/CreateOrder',
                request_serializer=payment__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=payment__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.VerifyPayment = channel.unary_unary(
                '/PaymentService/VerifyPayment',
                request_serializer=payment__pb2.PaymentVerifyRequest.SerializeToString,
                response_deserializer=payment__pb2.PaymentVerifyResponse.FromString,
                _registered_method=True)
        self.HandleWebhook = channel.unary_unary(
                '/PaymentService/HandleWebhook',
                request_serializer=payment__pb2.WebhookRequest.SerializeToString,
                response_deserializer=payment__pb2.WebhookResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/PaymentService/GetBalance',
                request_serializer=payment__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=payment__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.BindWithdrawAccount = channel.unary_unary(
                '/PaymentService/BindWithdrawAccount',
                request_serializer=payment__pb2.BindAccountRequest.SerializeToString,
                response_deserializer=payment__pb2.BindAccountResponse.FromString,
                _registered_method=True)
        self.Withdraw = channel.unary_unary(
                '/PaymentService/Withdraw',
                request_serializer=payment__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=payment__pb2.WithdrawResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/PaymentService/GetHistory',
                request_serializer=payment__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=payment__pb2.GetHistoryResponse.FromString,
                _registered_method=True)
        self.GetSubscription = channel.unary_unary(
                '/PaymentService/GetSubscription',
                request_serializer=payment__pb2.GetSubscriptionRequest.SerializeToString,
                response_deserializer=payment__pb2.GetSubscriptionResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """==========================================
    4. gRPC Service 定义
    ==========================================

    """

    def GetProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindWithdrawAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubscription(self, request, context):
        """查询用户当前订阅档位 + 到期时间(match-service 接入 SubscriptionTier 与配额判定)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducts,
                    request_deserializer=payment__pb2.GetProductsRequest.FromString,
                    response_serializer=payment__pb2.GetProductsResponse.SerializeToString,
            ),
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=payment__pb2.CreateOrderRequest.FromString,
                    response_serializer=payment__pb2.CreateOrderResponse.SerializeToString,
            ),
            'VerifyPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPayment,
                    request_deserializer=payment__pb2.PaymentVerifyRequest.FromString,
                    response_serializer=payment__pb2.PaymentVerifyResponse.SerializeToString,
            ),
            'HandleWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleWebhook,
                    request_deserializer=payment__pb2.WebhookRequest.FromString,
                    response_serializer=payment__pb2.WebhookResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=payment__pb2.GetBalanceRequest.FromString,
                    response_serializer=payment__pb2.GetBalanceResponse.SerializeToString,
            ),
            'BindWithdrawAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.BindWithdrawAccount,
                    request_deserializer=payment__pb2.BindAccountRequest.FromString,
                    response_serializer=payment__pb2.BindAccountResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=payment__pb2.WithdrawRequest.FromString,
                    response_serializer=payment__pb2.WithdrawResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=payment__pb2.GetHistoryRequest.FromString,
                    response_serializer=payment__pb2.GetHistoryResponse.SerializeToString,
            ),
            'GetSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubscription,
                    request_deserializer=payment__pb2.GetSubscriptionRequest.FromString,
                    response_serializer=payment__pb2.GetSubscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """==========================================
    4. gRPC Service 定义
    ==========================================

    """

    @staticmethod
    def GetProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/GetProducts',
            payment__pb2.GetProductsRequest.SerializeToString,
            payment__pb2.GetProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/CreateOrder',
            payment__pb2.CreateOrderRequest.SerializeToString,
            payment__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/VerifyPayment',
            payment__pb2.PaymentVerifyRequest.SerializeToString,
            payment__pb2.PaymentVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/HandleWebhook',
            payment__pb2.WebhookRequest.SerializeToString,
            payment__pb2.WebhookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/GetBalance',
            payment__pb2.GetBalanceRequest.SerializeToString,
            payment__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindWithdrawAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/BindWithdrawAccount',
            payment__pb2.BindAccountRequest.SerializeToString,
            payment__pb2.BindAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/Withdraw',
            payment__pb2.WithdrawRequest.SerializeToString,
            payment__pb2.WithdrawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/GetHistory',
            payment__pb2.GetHistoryRequest.SerializeToString,
            payment__pb2.GetHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/GetSubscription',
            payment__pb2.GetSubscriptionRequest.SerializeToString,
            payment__pb2.GetSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoinServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoins = channel.unary_unary(
                '/CoinService/GetCoins',
                request_serializer=payment__pb2.GetCoinsRequest.SerializeToString,
                response_deserializer=payment__pb2.GetCoinsResponse.FromString,
                _registered_method=True)
        self.GetCoinLedger = channel.unary_unary(
                '/CoinService/GetCoinLedger',
                request_serializer=payment__pb2.GetCoinLedgerRequest.SerializeToString,
                response_deserializer=payment__pb2.GetCoinLedgerResponse.FromString,
                _registered_method=True)
        self.AddCoins = channel.unary_unary(
                '/CoinService/AddCoins',
                request_serializer=payment__pb2.AddCoinsRequest.SerializeToString,
                response_deserializer=payment__pb2.AddCoinsResponse.FromString,
                _registered_method=True)
        self.AddPaidCoins = channel.unary_unary(
                '/CoinService/AddPaidCoins',
                request_serializer=payment__pb2.AddCoinsRequest.SerializeToString,
                response_deserializer=payment__pb2.AddCoinsResponse.FromString,
                _registered_method=True)
        self.ConsumeCoins = channel.unary_unary(
                '/CoinService/ConsumeCoins',
                request_serializer=payment__pb2.ConsumeCoinsRequest.SerializeToString,
                response_deserializer=payment__pb2.ConsumeCoinsResponse.FromString,
                _registered_method=True)


class CoinServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCoins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoinLedger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCoins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPaidCoins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeCoins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoinServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoins': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoins,
                    request_deserializer=payment__pb2.GetCoinsRequest.FromString,
                    response_serializer=payment__pb2.GetCoinsResponse.SerializeToString,
            ),
            'GetCoinLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoinLedger,
                    request_deserializer=payment__pb2.GetCoinLedgerRequest.FromString,
                    response_serializer=payment__pb2.GetCoinLedgerResponse.SerializeToString,
            ),
            'AddCoins': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCoins,
                    request_deserializer=payment__pb2.AddCoinsRequest.FromString,
                    response_serializer=payment__pb2.AddCoinsResponse.SerializeToString,
            ),
            'AddPaidCoins': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPaidCoins,
                    request_deserializer=payment__pb2.AddCoinsRequest.FromString,
                    response_serializer=payment__pb2.AddCoinsResponse.SerializeToString,
            ),
            'ConsumeCoins': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsumeCoins,
                    request_deserializer=payment__pb2.ConsumeCoinsRequest.FromString,
                    response_serializer=payment__pb2.ConsumeCoinsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CoinService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CoinService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoinService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCoins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoinService/GetCoins',
            payment__pb2.GetCoinsRequest.SerializeToString,
            payment__pb2.GetCoinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoinLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoinService/GetCoinLedger',
            payment__pb2.GetCoinLedgerRequest.SerializeToString,
            payment__pb2.GetCoinLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCoins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoinService/AddCoins',
            payment__pb2.AddCoinsRequest.SerializeToString,
            payment__pb2.AddCoinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPaidCoins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoinService/AddPaidCoins',
            payment__pb2.AddCoinsRequest.SerializeToString,
            payment__pb2.AddCoinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeCoins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoinService/ConsumeCoins',
            payment__pb2.ConsumeCoinsRequest.SerializeToString,
            payment__pb2.ConsumeCoinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
