# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/base_response.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common/base_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommon/base_response.proto\x12\x11\x63om.dating.common\"\x96\x01\n\x0c\x42\x61seResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x39\n\x05\x65xtra\x18\x03 \x03(\x0b\x32*.com.dating.common.BaseResponse.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\nPagination\x12\x13\n\x0bnext_cursor\x18\x01 \x01(\t\x12\x10\n\x08has_more\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.base_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASERESPONSE_EXTRAENTRY']._loaded_options = None
  _globals['_BASERESPONSE_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_BASERESPONSE']._serialized_start=50
  _globals['_BASERESPONSE']._serialized_end=200
  _globals['_BASERESPONSE_EXTRAENTRY']._serialized_start=156
  _globals['_BASERESPONSE_EXTRAENTRY']._serialized_end=200
  _globals['_PAGINATION']._serialized_start=202
  _globals['_PAGINATION']._serialized_end=253
# @@protoc_insertion_point(module_scope)
