# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import post_pb2 as post__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in post_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PostServiceStub(object):
    """=============================================================================
    post-service gRPC 接口契约

    规则:
    1. 一律业务主键 post_id / comment_id,**绝不暴露**内部自增 id(红线 12)。
    2. 操作人 user_id 由 mobile-gateway 解 JWT 后塞 Metadata "x-user-id" 透传,
    **不**作为业务字段塞 request(除非语义本身是"查谁的数据"如 ListUserPosts)。
    3. gRPC status code 一律 OK,业务错误用 base.code 区分(见 base_response.proto)。
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/com.dating.post.PostService/CreatePost',
                request_serializer=post__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=post__pb2.CreatePostResponse.FromString,
                _registered_method=True)
        self.GetPostDetail = channel.unary_unary(
                '/com.dating.post.PostService/GetPostDetail',
                request_serializer=post__pb2.GetPostDetailRequest.SerializeToString,
                response_deserializer=post__pb2.GetPostDetailResponse.FromString,
                _registered_method=True)
        self.ListUserPosts = channel.unary_unary(
                '/com.dating.post.PostService/ListUserPosts',
                request_serializer=post__pb2.ListUserPostsRequest.SerializeToString,
                response_deserializer=post__pb2.ListUserPostsResponse.FromString,
                _registered_method=True)
        self.DeletePost = channel.unary_unary(
                '/com.dating.post.PostService/DeletePost',
                request_serializer=post__pb2.DeletePostRequest.SerializeToString,
                response_deserializer=post__pb2.DeletePostResponse.FromString,
                _registered_method=True)
        self.ActionLike = channel.unary_unary(
                '/com.dating.post.PostService/ActionLike',
                request_serializer=post__pb2.ActionLikeRequest.SerializeToString,
                response_deserializer=post__pb2.ActionLikeResponse.FromString,
                _registered_method=True)
        self.CreateComment = channel.unary_unary(
                '/com.dating.post.PostService/CreateComment',
                request_serializer=post__pb2.CreateCommentRequest.SerializeToString,
                response_deserializer=post__pb2.CreateCommentResponse.FromString,
                _registered_method=True)
        self.ListComments = channel.unary_unary(
                '/com.dating.post.PostService/ListComments',
                request_serializer=post__pb2.ListCommentsRequest.SerializeToString,
                response_deserializer=post__pb2.ListCommentsResponse.FromString,
                _registered_method=True)
        self.DeleteComment = channel.unary_unary(
                '/com.dating.post.PostService/DeleteComment',
                request_serializer=post__pb2.DeleteCommentRequest.SerializeToString,
                response_deserializer=post__pb2.DeleteCommentResponse.FromString,
                _registered_method=True)
        self.GetRecommendFeed = channel.unary_unary(
                '/com.dating.post.PostService/GetRecommendFeed',
                request_serializer=post__pb2.GetRecommendFeedRequest.SerializeToString,
                response_deserializer=post__pb2.GetRecommendFeedResponse.FromString,
                _registered_method=True)


class PostServiceServicer(object):
    """=============================================================================
    post-service gRPC 接口契约

    规则:
    1. 一律业务主键 post_id / comment_id,**绝不暴露**内部自增 id(红线 12)。
    2. 操作人 user_id 由 mobile-gateway 解 JWT 后塞 Metadata "x-user-id" 透传,
    **不**作为业务字段塞 request(除非语义本身是"查谁的数据"如 ListUserPosts)。
    3. gRPC status code 一律 OK,业务错误用 base.code 区分(见 base_response.proto)。
    =============================================================================

    """

    def CreatePost(self, request, context):
        """发布帖子。content 必填、≤ 1024;image_keys 可空、≤ 9。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostDetail(self, request, context):
        """帖子详情。返回完整内容 + 图片 + 实时点赞/评论计数(DB 基准 + Redis 增量)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserPosts(self, request, context):
        """「TA 发的帖」列表,游标分页(雪花 ID 单调递增,作为游标即可)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """删除帖子(逻辑删除)。仅作者本人可删。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActionLike(self, request, context):
        """点赞 / 取消点赞。幂等。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """发评论(初版仅支持一级评论,楼中楼字段已预留)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListComments(self, request, context):
        """评论列表(一级评论,即 root_id=0),游标按 comment_id 倒序。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteComment(self, request, context):
        """删评论。仅作者本人可删。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendFeed(self, request, context):
        """推荐 Feed(性别分桶池 + 三路混合 + 布隆去重)。
        cursor 格式 "recOffset:csOffset",首次传 "0:0"。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=post__pb2.CreatePostRequest.FromString,
                    response_serializer=post__pb2.CreatePostResponse.SerializeToString,
            ),
            'GetPostDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostDetail,
                    request_deserializer=post__pb2.GetPostDetailRequest.FromString,
                    response_serializer=post__pb2.GetPostDetailResponse.SerializeToString,
            ),
            'ListUserPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserPosts,
                    request_deserializer=post__pb2.ListUserPostsRequest.FromString,
                    response_serializer=post__pb2.ListUserPostsResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=post__pb2.DeletePostRequest.FromString,
                    response_serializer=post__pb2.DeletePostResponse.SerializeToString,
            ),
            'ActionLike': grpc.unary_unary_rpc_method_handler(
                    servicer.ActionLike,
                    request_deserializer=post__pb2.ActionLikeRequest.FromString,
                    response_serializer=post__pb2.ActionLikeResponse.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=post__pb2.CreateCommentRequest.FromString,
                    response_serializer=post__pb2.CreateCommentResponse.SerializeToString,
            ),
            'ListComments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListComments,
                    request_deserializer=post__pb2.ListCommentsRequest.FromString,
                    response_serializer=post__pb2.ListCommentsResponse.SerializeToString,
            ),
            'DeleteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteComment,
                    request_deserializer=post__pb2.DeleteCommentRequest.FromString,
                    response_serializer=post__pb2.DeleteCommentResponse.SerializeToString,
            ),
            'GetRecommendFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendFeed,
                    request_deserializer=post__pb2.GetRecommendFeedRequest.FromString,
                    response_serializer=post__pb2.GetRecommendFeedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.dating.post.PostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.dating.post.PostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostService(object):
    """=============================================================================
    post-service gRPC 接口契约

    规则:
    1. 一律业务主键 post_id / comment_id,**绝不暴露**内部自增 id(红线 12)。
    2. 操作人 user_id 由 mobile-gateway 解 JWT 后塞 Metadata "x-user-id" 透传,
    **不**作为业务字段塞 request(除非语义本身是"查谁的数据"如 ListUserPosts)。
    3. gRPC status code 一律 OK,业务错误用 base.code 区分(见 base_response.proto)。
    =============================================================================

    """

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/CreatePost',
            post__pb2.CreatePostRequest.SerializeToString,
            post__pb2.CreatePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/GetPostDetail',
            post__pb2.GetPostDetailRequest.SerializeToString,
            post__pb2.GetPostDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/ListUserPosts',
            post__pb2.ListUserPostsRequest.SerializeToString,
            post__pb2.ListUserPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/DeletePost',
            post__pb2.DeletePostRequest.SerializeToString,
            post__pb2.DeletePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActionLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/ActionLike',
            post__pb2.ActionLikeRequest.SerializeToString,
            post__pb2.ActionLikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/CreateComment',
            post__pb2.CreateCommentRequest.SerializeToString,
            post__pb2.CreateCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/ListComments',
            post__pb2.ListCommentsRequest.SerializeToString,
            post__pb2.ListCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/DeleteComment',
            post__pb2.DeleteCommentRequest.SerializeToString,
            post__pb2.DeleteCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.dating.post.PostService/GetRecommendFeed',
            post__pb2.GetRecommendFeedRequest.SerializeToString,
            post__pb2.GetRecommendFeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
