# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import im_pb2 as im__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in im_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnRawCallback = channel.unary_unary(
                '/ImService/OnRawCallback',
                request_serializer=im__pb2.RawCallback.SerializeToString,
                response_deserializer=im__pb2.OnRawCallbackResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/ImService/SendMessage',
                request_serializer=im__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=im__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.GetImToken = channel.unary_unary(
                '/ImService/GetImToken',
                request_serializer=im__pb2.GetImTokenRequest.SerializeToString,
                response_deserializer=im__pb2.GetImTokenResponse.FromString,
                _registered_method=True)
        self.RegisterImUser = channel.unary_unary(
                '/ImService/RegisterImUser',
                request_serializer=im__pb2.RegisterImUserRequest.SerializeToString,
                response_deserializer=im__pb2.RegisterImUserResponse.FromString,
                _registered_method=True)
        self.GenerateCallToken = channel.unary_unary(
                '/ImService/GenerateCallToken',
                request_serializer=im__pb2.GenerateCallTokenRequest.SerializeToString,
                response_deserializer=im__pb2.GenerateCallTokenResponse.FromString,
                _registered_method=True)
        self.SendBusinessNotification = channel.unary_unary(
                '/ImService/SendBusinessNotification',
                request_serializer=im__pb2.SendBusinessNotificationRequest.SerializeToString,
                response_deserializer=im__pb2.SendBusinessNotificationResponse.FromString,
                _registered_method=True)
        self.SendMatchSuccess = channel.unary_unary(
                '/ImService/SendMatchSuccess',
                request_serializer=im__pb2.SendMatchSuccessRequest.SerializeToString,
                response_deserializer=im__pb2.SendMatchSuccessResponse.FromString,
                _registered_method=True)
        self.ListOnlineUserIds = channel.unary_unary(
                '/ImService/ListOnlineUserIds',
                request_serializer=im__pb2.ListOnlineUserIdsRequest.SerializeToString,
                response_deserializer=im__pb2.ListOnlineUserIdsResponse.FromString,
                _registered_method=True)
        self.ListRecentOfflineUsers = channel.unary_unary(
                '/ImService/ListRecentOfflineUsers',
                request_serializer=im__pb2.ListRecentOfflineUsersRequest.SerializeToString,
                response_deserializer=im__pb2.ListRecentOfflineUsersResponse.FromString,
                _registered_method=True)


class ImServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnRawCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterImUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCallToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBusinessNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMatchSuccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOnlineUserIds(self, request, context):
        """拉本窗口内「新建立 OpenIM 会话」的真人 userId 列表。
        实现:ZRANGEBYSCORE im:presence:online since_ms until_ms LIMIT 0 limit
        (score = online_at,ZADD NX 写入,会话期间不变,因此窗口只覆盖本周期新上线的用户)。
        DH 用户无 IM 设备登录,天然不会进 im:presence:online,返回值不含 DH。
        用途:match-service OnlinePlanGenerator(见 dating-server/docs/match-service-prd-tech.md §6.3.1)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRecentOfflineUsers(self, request, context):
        """拉本窗口内「OpenIM 下线回调已收口」的真人 userId 列表。
        实现:SELECT user_id FROM user_online_session
        WHERE offline_at >= :since AND offline_at < :until AND deleted = false
        ORDER BY offline_at LIMIT :limit
        (走 partial index idx_uos_offline_at)。同样天然不含 DH。
        用途:match-service OfflinePlanGenerator(见 §6.3.2)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnRawCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.OnRawCallback,
                    request_deserializer=im__pb2.RawCallback.FromString,
                    response_serializer=im__pb2.OnRawCallbackResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=im__pb2.SendMessageRequest.FromString,
                    response_serializer=im__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetImToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImToken,
                    request_deserializer=im__pb2.GetImTokenRequest.FromString,
                    response_serializer=im__pb2.GetImTokenResponse.SerializeToString,
            ),
            'RegisterImUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterImUser,
                    request_deserializer=im__pb2.RegisterImUserRequest.FromString,
                    response_serializer=im__pb2.RegisterImUserResponse.SerializeToString,
            ),
            'GenerateCallToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCallToken,
                    request_deserializer=im__pb2.GenerateCallTokenRequest.FromString,
                    response_serializer=im__pb2.GenerateCallTokenResponse.SerializeToString,
            ),
            'SendBusinessNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBusinessNotification,
                    request_deserializer=im__pb2.SendBusinessNotificationRequest.FromString,
                    response_serializer=im__pb2.SendBusinessNotificationResponse.SerializeToString,
            ),
            'SendMatchSuccess': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMatchSuccess,
                    request_deserializer=im__pb2.SendMatchSuccessRequest.FromString,
                    response_serializer=im__pb2.SendMatchSuccessResponse.SerializeToString,
            ),
            'ListOnlineUserIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOnlineUserIds,
                    request_deserializer=im__pb2.ListOnlineUserIdsRequest.FromString,
                    response_serializer=im__pb2.ListOnlineUserIdsResponse.SerializeToString,
            ),
            'ListRecentOfflineUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecentOfflineUsers,
                    request_deserializer=im__pb2.ListRecentOfflineUsersRequest.FromString,
                    response_serializer=im__pb2.ListRecentOfflineUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ImService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnRawCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/OnRawCallback',
            im__pb2.RawCallback.SerializeToString,
            im__pb2.OnRawCallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/SendMessage',
            im__pb2.SendMessageRequest.SerializeToString,
            im__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/GetImToken',
            im__pb2.GetImTokenRequest.SerializeToString,
            im__pb2.GetImTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterImUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/RegisterImUser',
            im__pb2.RegisterImUserRequest.SerializeToString,
            im__pb2.RegisterImUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCallToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/GenerateCallToken',
            im__pb2.GenerateCallTokenRequest.SerializeToString,
            im__pb2.GenerateCallTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBusinessNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/SendBusinessNotification',
            im__pb2.SendBusinessNotificationRequest.SerializeToString,
            im__pb2.SendBusinessNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMatchSuccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/SendMatchSuccess',
            im__pb2.SendMatchSuccessRequest.SerializeToString,
            im__pb2.SendMatchSuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOnlineUserIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/ListOnlineUserIds',
            im__pb2.ListOnlineUserIdsRequest.SerializeToString,
            im__pb2.ListOnlineUserIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRecentOfflineUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImService/ListRecentOfflineUsers',
            im__pb2.ListRecentOfflineUsersRequest.SerializeToString,
            im__pb2.ListRecentOfflineUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
